### ISSUE TITLE
Cannot write Function - cannot serialize Datascript DB containing functions

### ISSUE THREAD

**Issue by jamesnyika** [tonsky/datascript-transit#6]
Hi @tonsky 
I am trying to serialize my datascript database to JSON for storage in my React Native app using the Expo.io File System capability. The idea is to generate a string from the DB using datascript-transit and then use expo-file-system to write to a file internally on device. 

 Some of the data inside my database includes functions. For reasons that are not interesting, I need to store them in the database for now with other session info for the application. But I get an exception that transit "cannot write Function" 

Is this a problem here or in Transit and do you have any suggestions for how to fix this ? Any debug flag that can help me figure out where it is choking ? Hope I do not have to handle writing this myself. .. 

![Simulator Screen Shot - iPhone X - 2019-07-23 at 23 01 48](https://user-images.githubusercontent.com/6818081/61761826-e41bab00-ad9d-11e9-8548-ad4a2e85dc1e.png)

**Comment by tonsky** [comment]
Hi @jamesnyika! There’s no way to serialize a function. Consider storing function names in DB instead, those are easily serializable
